#ifndef __SOUND_MAPPINGS__
#define __SOUND_MAPPINGS__

#include "sounds.h"
#include <cstdint>

const char* instrument_sounds[] = { 
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr, // "A.Bass Dr",
    sound_kick1, // "Bass Dr 1",
    nullptr, // "S. Stick",
    sound_snare, // "A. Snare",
    sound_clap, // "Hand Clap",
    nullptr, // "E. Snare",
    nullptr, // "Low F Tom",
    sound_clhihat, // "Cl. HiHat",
    nullptr, // "H. F Tom",
    nullptr, // "P. HiHat",
    nullptr, // "Low Tom",
    sound_ohihat, // "O. HiHat",
    nullptr, // "L.Mid Tom",
    nullptr, // "H.Mid Tom",
    sound_crash1, // "Crash 1",
    sound_hitom, // "High Tom",
    sound_ride1, // "Ride 1",
    nullptr, // "Chinese",
    nullptr, // "Ride Bell",
    nullptr, // "Tambourin",
    nullptr, // "Splash C.",
    nullptr, // "Cowbell",
    nullptr, // "Crash 2",
    nullptr, // "Vibraslap",
    nullptr, // "Ride C. 2",
    nullptr, // "Hi Bongo",
    nullptr, // "Low Bongo",
    nullptr, // "M.Hi Conga",
    nullptr, // "O. Hi Conga",
    nullptr, // "Low Conga",
    nullptr, // "H. Timbale",
    nullptr, // "L. Timbale",
    nullptr, // "Hi. Agogo",
    nullptr, // "Low Agogo",
    nullptr, // "Cabasa",
    nullptr, // "Maracas",
    nullptr, // "S. Whistle",
    nullptr, // "L. Whistle",
    nullptr, // "S. Guiro",
    nullptr, // "L. Guiro",
    nullptr, // "Claves",
    nullptr, // "H. Wood Bl.",
    nullptr, // "L. Wood Bl.",
    nullptr, // "Mute Cuica",
    nullptr, // "Open Cuica",
    nullptr, // "M.Triangle",
    nullptr, // "O.Triangle",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr 
};

const size_t instrument_sounds_len[] = { 
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0, // "A.Bass Dr",
    sound_kick1_length, // "Bass Dr 1",
    0, // "S. Stick",
    sound_snare_length, // "A. Snare",
    sound_clap_length, // "Hand Clap",
    0, // "E. Snare",
    0, // "Low F Tom",
    sound_clhihat_length, // "Cl. HiHat",
    0, // "H. F Tom",
    0, // "P. HiHat",
    0, // "Low Tom",
    sound_ohihat_length, // "O. HiHat",
    sound_lmidtom_length, // "L.Mid Tom",
    0, // "H.Mid Tom",
    sound_crash1_length, // "Crash 1",
    sound_hitom_length, // "High Tom",
    sound_ride1_length, // "Ride 1",
    0, // "Chinese",
    0, // "Ride Bell",
    0, // "Tambourin",
    0, // "Splash C.",
    0, // "Cowbell",
    0, // "Crash 2",
    0, // "Vibraslap",
    0, // "Ride C. 2",
    0, // "Hi Bongo",
    0, // "Low Bongo",
    0, // "M.Hi Conga",
    0, // "O. Hi Conga",
    0, // "Low Conga",
    0, // "H. Timbale",
    0, // "L. Timbale",
    0, // "Hi. Agogo",
    0, // "Low Agogo",
    0, // "Cabasa",
    0, // "Maracas",
    0, // "S. Whistle",
    0, // "L. Whistle",
    0, // "S. Guiro",
    0, // "L. Guiro",
    0, // "Claves",
    0, // "H. Wood Bl.",
    0, // "L. Wood Bl.",
    0, // "Mute Cuica",
    0, // "Open Cuica",
    0, // "M.Triangle",
    0, // "O.Triangle",
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0 
};

#endif